mysql_config:
  protocol: "tcp"
  host: "api.ikanned.com"
  port: 24401
  username: "test_stay"
  password: "TcRSI4UYQN6wP6XWE7"
  database: "test_stay_db"
wx_app:
  app_id: "wxid"
  app_secret: "ferghnytejtd"